//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Closing_Contract
    {
        public int ID_Contract { get; set; }
        public System.DateTime Date_Of_Closing { get; set; }
        public string Reason { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
