//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountToItem
    {
        public int DiscItemId { get; set; }
        public int StorehouseItemId { get; set; }
        public int DiscountId { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual StorehouseItem StorehouseItem { get; set; }
    }
}
