//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firm
    {
        public int ID_Customer { get; set; }
        public string Company_Name { get; set; }
        public string Physical_Adress { get; set; }
        public int Phone_Number { get; set; }
        public string Password { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
