//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternetProviderEntities : DbContext
    {
        public InternetProviderEntities()
            : base("name=InternetProviderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Closing_Contract> Closing_Contract { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Physical> Physical { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tariff_Plan> Tariff_Plan { get; set; }
        public virtual DbSet<Additional_Services> Additional_Services { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<вДоговір> вДоговір { get; set; }
        public virtual DbSet<вПрацівники> вПрацівники { get; set; }
        public virtual DbSet<вПрацівники2> вПрацівники2 { get; set; }
    }
}
