//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Quantity { get; set; }
        public int SaleId { get; set; }
        public int CheckId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public Nullable<int> StorehouseItemId { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual StorehouseItem StorehouseItem { get; set; }
    }
}
