//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ID_Services { get; set; }
        public string Name_Of_Services { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Additional_Services Additional_Services { get; set; }
    }
}
