//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class вДоговір
    {
        public int код_тарифного_плана { get; set; }
        public string прізвище { get; set; }
        public string імя { get; set; }
        public string побатькові { get; set; }
        public string фіз_адреса { get; set; }
        public Nullable<int> код_працівника { get; set; }
        public string назва { get; set; }
        public Nullable<decimal> ціна { get; set; }
    }
}
