//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class вПрацівники
    {
        public Nullable<int> код_працівника { get; set; }
        public string прізвище { get; set; }
        public string імя { get; set; }
        public string побатькові { get; set; }
        public string назва_посади { get; set; }
        public Nullable<decimal> зарплата { get; set; }
        public Nullable<int> код_клієнта { get; set; }
    }
}
